### ISSUE TITLE
Week 1 Crossover Review Ticket

### ISSUE THREAD

**Issue by ashwinbabu888** [nolanplatt/AP-CSA-T2#15]

**Comment by ChiefGuap** [comment]
Theme all the information toward project approval.

Scrum Team Project Review

**Design - Wiki Theme, Brain Write & Wire Frame**
Overall, everything was there for wiki theme, brain write and wire frame. They had a really cool visual on what their website is going to be, and I got a full understanding on what their project is going to be and the direction that they are heading into. 
Score; 1/1



**Technicals - 10  to 12 key ideas**
They had their list of the technical and showed what was going to be on the website in the near future. Rather than putting it on the ReadMe, I would suggest that it should be on the wiki page as the ReadMe page should just be like pictures and main ideas. Overall, great job. 
Score: 1/1

**Github - On Wiki containing Management Plan, forking, branching, pull request, etc**
This was located on a contributing guidelines markdown within a docs folder rather than being located on the wiki page. The information is really good and well written, but not in the right location. But it looks really good! 
Score: 0.9/1


**Deployment - On Wiki containing Hardware, frequency, etc and Scrum Board - Assignments and Backlog**
The deployment guide was well written with tons of good information and included a frequency on when they are going to deploy weekly! They really hit the key details, and I really loved how the scrum board looks like as each issue ticket has a indication on which week it was associated to, which is really awesome in my opinion! Overall, great job! 
Score: 1/1


**Final Score: 3.9/4**

**Comment by jm1021** [comment]
PurpleTeam - Ashwin 4.9/5
* Wire frames are nice. Problems loading .9/1
* Admin panel, login, other services 1/1
* Github policy 1/1
* Deployment procedure, need update 1/1
* Scrum board has nice week tags. 1/1
